In [25]:
import pandas as pd

In [26]:
file_path = "../data/interim/cleaned_insurance.xlsx"
medical = pd.read_excel(file_path)
medical.head(10)

   Unnamed: 0  age     sex   bmi  children smoker     region  expenses
0           0   19  female  27.9         0    yes  southwest  16884.92
1           1   18    male  33.8         1     no  southeast   1725.55
2           2   28    male  33.0         3     no  southeast   4449.46
3           3   33    male  22.7         0     no  northwest  21984.47
4           4   32    male  28.9         0     no  northwest   3866.86
5           5   31  female  25.7         0     no  southeast   3756.62
6           6   46  female  33.4         1     no  southeast   8240.59
7           7   37  female  27.7         3     no  northwest   7281.51
8           8   37    male  29.8         2     no  northeast   6406.41
9           9   60  female  25.8         0     no  northwest  28923.14

In [27]:
print("no.of missing values:", medical.isna().sum())
print("no.of duplicatedd values:", medical.duplicated().sum())

no.of missing values: Unnamed: 0    0
age           0
sex           0
bmi           0
children      0
smoker        0
region        0
expenses      0
dtype: int64
no.of duplicatedd values: 0

In [28]:
medical = medical.drop(columns= ["Unnamed: 0"])

In [29]:
medical

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1332   50    male  31.0         3     no  northwest  10600.55
1333   18  female  31.9         0     no  northeast   2205.98
1334   18  female  36.9         0     no  southeast   1629.83
1335   21  female  25.8         0     no  southwest   2007.95
1336   61  female  29.1         0    yes  northwest  29141.36

[1337 rows x 7 columns]

In [30]:
medical = pd.get_dummies(medical, columns=["sex"],dtype=int)

In [31]:
medical.head()

   age   bmi  children smoker     region  expenses  sex_female  sex_male
0   19  27.9         0    yes  southwest  16884.92           1         0
1   18  33.8         1     no  southeast   1725.55           0         1
2   28  33.0         3     no  southeast   4449.46           0         1
3   33  22.7         0     no  northwest  21984.47           0         1
4   32  28.9         0     no  northwest   3866.86           0         1

In [32]:
medical = pd.get_dummies(medical, columns= ["smoker"], dtype= int)

In [33]:
medical.head()

,age,bmi,children,region,expenses,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.9,0,southwest,16884.92,1,0,0,1
1,18,33.8,1,southeast,1725.55,0,1,1,0
2,28,33.0,3,southeast,4449.46,0,1,1,0
3,33,22.7,0,northwest,21984.47,0,1,1,0
4,32,28.9,0,northwest,3866.86,0,1,1,0

In [34]:
medical["region"].unique()

<ArrowStringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [36]:
medical.head()

,age,bmi,children,region,expenses,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.9,0,southwest,16884.92,1,0,0,1
1,18,33.8,1,southeast,1725.55,0,1,1,0
2,28,33.0,3,southeast,4449.46,0,1,1,0
3,33,22.7,0,northwest,21984.47,0,1,1,0
4,32,28.9,0,northwest,3866.86,0,1,1,0

In [37]:
medical = medical.drop(columns= ["region"])

In [38]:
medical

,age,bmi,children,expenses,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.9,0,16884.92,1,0,0,1
1,18,33.8,1,1725.55,0,1,1,0
2,28,33.0,3,4449.46,0,1,1,0
3,33,22.7,0,21984.47,0,1,1,0
4,32,28.9,0,3866.86,0,1,1,0
...,...,...,...,...,...,...,...,...
1332,50,31.0,3,10600.55,0,1,1,0
1333,18,31.9,0,2205.98,1,0,1,0
1334,18,36.9,0,1629.83,1,0,1,0
1335,21,25.8,0,2007.95,1,0,1,0
1336,61,29.1,0,29141.36,1,0,0,1