In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
medical = pd.read_excel("../data/interim/transformed_insurance.xlsx")
medical.head()

   Unnamed: 0  age   bmi  children  ...  sex_male  smoker_no  smoker_yes  age_smoker
0           0   19  27.9         0  ...         0          0           1          19
1           1   18  33.8         1  ...         1          1           0           0
2           2   28  33.0         3  ...         1          1           0           0
3           3   33  22.7         0  ...         1          1           0           0
4           4   32  28.9         0  ...         1          1           0           0

[5 rows x 10 columns]

In [3]:
medical = medical.drop(columns=["children"], axis=0)

In [4]:
medical.head()

   Unnamed: 0  age   bmi  expenses  ...  sex_male  smoker_no  smoker_yes  age_smoker
0           0   19  27.9  16884.92  ...         0          0           1          19
1           1   18  33.8   1725.55  ...         1          1           0           0
2           2   28  33.0   4449.46  ...         1          1           0           0
3           3   33  22.7  21984.47  ...         1          1           0           0
4           4   32  28.9   3866.86  ...         1          1           0           0

[5 rows x 9 columns]

In [5]:
x = medical.drop(columns=["expenses"])
y= medical["expenses"]

In [6]:
x

      Unnamed: 0  age   bmi  ...  smoker_no  smoker_yes  age_smoker
0              0   19  27.9  ...          0           1          19
1              1   18  33.8  ...          1           0           0
2              2   28  33.0  ...          1           0           0
3              3   33  22.7  ...          1           0           0
4              4   32  28.9  ...          1           0           0
...          ...  ...   ...  ...        ...         ...         ...
1332        1332   50  31.0  ...          1           0           0
1333        1333   18  31.9  ...          1           0           0
1334        1334   18  36.9  ...          1           0           0
1335        1335   21  25.8  ...          1           0           0
1336        1336   61  29.1  ...          0           1          61

[1337 rows x 8 columns]

In [7]:
y

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1332    10600.55
1333     2205.98
1334     1629.83
1335     2007.95
1336    29141.36
Name: expenses, Length: 1337, dtype: float64

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [9]:
medical.to_excel("../data/interim/featured_insurance.xlsx")